language: php
sudo: false

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - hhvm

env:
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*
    - SYMFONY_VERSION=3.1.*
    - SYMFONY_VERSION=3.2.*
    - SYMFONY_VERSION=3.3.*

services:
    - redis-server

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] &&  [ "$TRAVIS_PHP_VERSION" < "7.1" ]; then phpenv config-rm xdebug.ini; fi
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv rehash; fi;
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
    - composer install

script:
    - ./vendor/bin/phpunit
